/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrgRouteRouteImport } from './routes/org/route'
import { Route as SairRouteImport } from './routes/sair'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAlertasRouteImport } from './routes/app/alertas'
import { Route as AppConfiguracoesRouteImport } from './routes/app/configuracoes'
import { Route as AppContestacaoRouteImport } from './routes/app/contestacao'
import { Route as AppLumiaRouteImport } from './routes/app/lumia'
import { Route as AppMapaRouteImport } from './routes/app/mapa'
import { Route as AppOcorrenciasRouteImport } from './routes/app/ocorrencias'
import { Route as AppPrivacidadeRouteImport } from './routes/app/privacidade'
import { Route as AppRegistrarRouteImport } from './routes/app/registrar'
import { Route as InstitucionalCadastroRouteImport } from './routes/institucional/cadastro'
import { Route as InstitucionalEntrarRouteImport } from './routes/institucional/entrar'
import { Route as InstitucionalEsqueciSenhaRouteImport } from './routes/institucional/esqueci-senha'
import { Route as OrgIndexRouteImport } from './routes/org/index'
import { Route as OrgAnalisesRouteImport } from './routes/org/analises'
import { Route as OrgAuditoriaRouteImport } from './routes/org/auditoria'
import { Route as OrgConfiguracoesRouteImport } from './routes/org/configuracoes'
import { Route as OrgContestacoesRouteImport } from './routes/org/contestacoes'
import { Route as OrgMapaRouteImport } from './routes/org/mapa'
import { Route as OrgNotificacoesRouteImport } from './routes/org/notificacoes'
import { Route as OrgOcorrenciasRouteImport } from './routes/org/ocorrencias'
import { Route as OrgPopulacaoRouteImport } from './routes/org/populacao'
import { Route as OrgPrevisoesRouteImport } from './routes/org/previsoes'
import { Route as OrgRelatoriosRouteImport } from './routes/org/relatorios'
import { Route as OrgAuditoriaLogsRouteImport } from './routes/org/auditoria.logs'
import { Route as OrgContestacoesRevisaoRouteImport } from './routes/org/contestacoes.revisao'
import { Route as OrgPrevisoesExplicacaoRouteImport } from './routes/org/previsoes.explicacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRouteRoute = OrgRouteRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const SairRoute = SairRouteImport.update({
  id: '/sair',
  path: '/sair',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContestacaoRoute = AppContestacaoRouteImport.update({
  id: '/contestacao',
  path: '/contestacao',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLumiaRoute = AppLumiaRouteImport.update({
  id: '/lumia',
  path: '/lumia',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMapaRoute = AppMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOcorrenciasRoute = AppOcorrenciasRouteImport.update({
  id: '/ocorrencias',
  path: '/ocorrencias',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPrivacidadeRoute = AppPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRegistrarRoute = AppRegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => AppRouteRoute,
} as any)
const InstitucionalCadastroRoute = InstitucionalCadastroRouteImport.update({
  id: '/institucional/cadastro',
  path: '/institucional/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalEntrarRoute = InstitucionalEntrarRouteImport.update({
  id: '/institucional/entrar',
  path: '/institucional/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalEsqueciSenhaRoute =
  InstitucionalEsqueciSenhaRouteImport.update({
    id: '/institucional/esqueci-senha',
    path: '/institucional/esqueci-senha',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgAnalisesRoute = OrgAnalisesRouteImport.update({
  id: '/analises',
  path: '/analises',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgAuditoriaRoute = OrgAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgConfiguracoesRoute = OrgConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgContestacoesRoute = OrgContestacoesRouteImport.update({
  id: '/contestacoes',
  path: '/contestacoes',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgMapaRoute = OrgMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgNotificacoesRoute = OrgNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgOcorrenciasRoute = OrgOcorrenciasRouteImport.update({
  id: '/ocorrencias',
  path: '/ocorrencias',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgPopulacaoRoute = OrgPopulacaoRouteImport.update({
  id: '/populacao',
  path: '/populacao',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgPrevisoesRoute = OrgPrevisoesRouteImport.update({
  id: '/previsoes',
  path: '/previsoes',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgRelatoriosRoute = OrgRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgAuditoriaLogsRoute = OrgAuditoriaLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => OrgAuditoriaRoute,
} as any)
const OrgContestacoesRevisaoRoute = OrgContestacoesRevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => OrgContestacoesRoute,
} as any)
const OrgPrevisoesExplicacaoRoute = OrgPrevisoesExplicacaoRouteImport.update({
  id: '/explicacao',
  path: '/explicacao',
  getParentRoute: () => OrgPrevisoesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/org': typeof OrgRouteRouteWithChildren
  '/acesso': typeof AcessoRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/onboarding': typeof OnboardingRoute
  '/sair': typeof SairRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contestacao': typeof AppContestacaoRoute
  '/app/lumia': typeof AppLumiaRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/ocorrencias': typeof AppOcorrenciasRoute
  '/app/privacidade': typeof AppPrivacidadeRoute
  '/app/registrar': typeof AppRegistrarRoute
  '/institucional/cadastro': typeof InstitucionalCadastroRoute
  '/institucional/entrar': typeof InstitucionalEntrarRoute
  '/institucional/esqueci-senha': typeof InstitucionalEsqueciSenhaRoute
  '/org/analises': typeof OrgAnalisesRoute
  '/org/auditoria': typeof OrgAuditoriaRouteWithChildren
  '/org/configuracoes': typeof OrgConfiguracoesRoute
  '/org/contestacoes': typeof OrgContestacoesRouteWithChildren
  '/org/mapa': typeof OrgMapaRoute
  '/org/notificacoes': typeof OrgNotificacoesRoute
  '/org/ocorrencias': typeof OrgOcorrenciasRoute
  '/org/populacao': typeof OrgPopulacaoRoute
  '/org/previsoes': typeof OrgPrevisoesRouteWithChildren
  '/org/relatorios': typeof OrgRelatoriosRoute
  '/app/': typeof AppIndexRoute
  '/org/': typeof OrgIndexRoute
  '/org/auditoria/logs': typeof OrgAuditoriaLogsRoute
  '/org/contestacoes/revisao': typeof OrgContestacoesRevisaoRoute
  '/org/previsoes/explicacao': typeof OrgPrevisoesExplicacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/onboarding': typeof OnboardingRoute
  '/sair': typeof SairRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contestacao': typeof AppContestacaoRoute
  '/app/lumia': typeof AppLumiaRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/ocorrencias': typeof AppOcorrenciasRoute
  '/app/privacidade': typeof AppPrivacidadeRoute
  '/app/registrar': typeof AppRegistrarRoute
  '/institucional/cadastro': typeof InstitucionalCadastroRoute
  '/institucional/entrar': typeof InstitucionalEntrarRoute
  '/institucional/esqueci-senha': typeof InstitucionalEsqueciSenhaRoute
  '/org/analises': typeof OrgAnalisesRoute
  '/org/auditoria': typeof OrgAuditoriaRouteWithChildren
  '/org/configuracoes': typeof OrgConfiguracoesRoute
  '/org/contestacoes': typeof OrgContestacoesRouteWithChildren
  '/org/mapa': typeof OrgMapaRoute
  '/org/notificacoes': typeof OrgNotificacoesRoute
  '/org/ocorrencias': typeof OrgOcorrenciasRoute
  '/org/populacao': typeof OrgPopulacaoRoute
  '/org/previsoes': typeof OrgPrevisoesRouteWithChildren
  '/org/relatorios': typeof OrgRelatoriosRoute
  '/app': typeof AppIndexRoute
  '/org': typeof OrgIndexRoute
  '/org/auditoria/logs': typeof OrgAuditoriaLogsRoute
  '/org/contestacoes/revisao': typeof OrgContestacoesRevisaoRoute
  '/org/previsoes/explicacao': typeof OrgPrevisoesExplicacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/org': typeof OrgRouteRouteWithChildren
  '/acesso': typeof AcessoRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/onboarding': typeof OnboardingRoute
  '/sair': typeof SairRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contestacao': typeof AppContestacaoRoute
  '/app/lumia': typeof AppLumiaRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/ocorrencias': typeof AppOcorrenciasRoute
  '/app/privacidade': typeof AppPrivacidadeRoute
  '/app/registrar': typeof AppRegistrarRoute
  '/institucional/cadastro': typeof InstitucionalCadastroRoute
  '/institucional/entrar': typeof InstitucionalEntrarRoute
  '/institucional/esqueci-senha': typeof InstitucionalEsqueciSenhaRoute
  '/org/analises': typeof OrgAnalisesRoute
  '/org/auditoria': typeof OrgAuditoriaRouteWithChildren
  '/org/configuracoes': typeof OrgConfiguracoesRoute
  '/org/contestacoes': typeof OrgContestacoesRouteWithChildren
  '/org/mapa': typeof OrgMapaRoute
  '/org/notificacoes': typeof OrgNotificacoesRoute
  '/org/ocorrencias': typeof OrgOcorrenciasRoute
  '/org/populacao': typeof OrgPopulacaoRoute
  '/org/previsoes': typeof OrgPrevisoesRouteWithChildren
  '/org/relatorios': typeof OrgRelatoriosRoute
  '/app/': typeof AppIndexRoute
  '/org/': typeof OrgIndexRoute
  '/org/auditoria/logs': typeof OrgAuditoriaLogsRoute
  '/org/contestacoes/revisao': typeof OrgContestacoesRevisaoRoute
  '/org/previsoes/explicacao': typeof OrgPrevisoesExplicacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/org'
    | '/acesso'
    | '/cadastro'
    | '/entrar'
    | '/esqueci-senha'
    | '/onboarding'
    | '/sair'
    | '/app/alertas'
    | '/app/configuracoes'
    | '/app/contestacao'
    | '/app/lumia'
    | '/app/mapa'
    | '/app/ocorrencias'
    | '/app/privacidade'
    | '/app/registrar'
    | '/institucional/cadastro'
    | '/institucional/entrar'
    | '/institucional/esqueci-senha'
    | '/org/analises'
    | '/org/auditoria'
    | '/org/configuracoes'
    | '/org/contestacoes'
    | '/org/mapa'
    | '/org/notificacoes'
    | '/org/ocorrencias'
    | '/org/populacao'
    | '/org/previsoes'
    | '/org/relatorios'
    | '/app/'
    | '/org/'
    | '/org/auditoria/logs'
    | '/org/contestacoes/revisao'
    | '/org/previsoes/explicacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso'
    | '/cadastro'
    | '/entrar'
    | '/esqueci-senha'
    | '/onboarding'
    | '/sair'
    | '/app/alertas'
    | '/app/configuracoes'
    | '/app/contestacao'
    | '/app/lumia'
    | '/app/mapa'
    | '/app/ocorrencias'
    | '/app/privacidade'
    | '/app/registrar'
    | '/institucional/cadastro'
    | '/institucional/entrar'
    | '/institucional/esqueci-senha'
    | '/org/analises'
    | '/org/auditoria'
    | '/org/configuracoes'
    | '/org/contestacoes'
    | '/org/mapa'
    | '/org/notificacoes'
    | '/org/ocorrencias'
    | '/org/populacao'
    | '/org/previsoes'
    | '/org/relatorios'
    | '/app'
    | '/org'
    | '/org/auditoria/logs'
    | '/org/contestacoes/revisao'
    | '/org/previsoes/explicacao'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/org'
    | '/acesso'
    | '/cadastro'
    | '/entrar'
    | '/esqueci-senha'
    | '/onboarding'
    | '/sair'
    | '/app/alertas'
    | '/app/configuracoes'
    | '/app/contestacao'
    | '/app/lumia'
    | '/app/mapa'
    | '/app/ocorrencias'
    | '/app/privacidade'
    | '/app/registrar'
    | '/institucional/cadastro'
    | '/institucional/entrar'
    | '/institucional/esqueci-senha'
    | '/org/analises'
    | '/org/auditoria'
    | '/org/configuracoes'
    | '/org/contestacoes'
    | '/org/mapa'
    | '/org/notificacoes'
    | '/org/ocorrencias'
    | '/org/populacao'
    | '/org/previsoes'
    | '/org/relatorios'
    | '/app/'
    | '/org/'
    | '/org/auditoria/logs'
    | '/org/contestacoes/revisao'
    | '/org/previsoes/explicacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  OrgRouteRoute: typeof OrgRouteRouteWithChildren
  AcessoRoute: typeof AcessoRoute
  CadastroRoute: typeof CadastroRoute
  EntrarRoute: typeof EntrarRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  OnboardingRoute: typeof OnboardingRoute
  SairRoute: typeof SairRoute
  InstitucionalCadastroRoute: typeof InstitucionalCadastroRoute
  InstitucionalEntrarRoute: typeof InstitucionalEntrarRoute
  InstitucionalEsqueciSenhaRoute: typeof InstitucionalEsqueciSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sair': {
      id: '/sair'
      path: '/sair'
      fullPath: '/sair'
      preLoaderRoute: typeof SairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/alertas': {
      id: '/app/alertas'
      path: '/alertas'
      fullPath: '/app/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/contestacao': {
      id: '/app/contestacao'
      path: '/contestacao'
      fullPath: '/app/contestacao'
      preLoaderRoute: typeof AppContestacaoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/lumia': {
      id: '/app/lumia'
      path: '/lumia'
      fullPath: '/app/lumia'
      preLoaderRoute: typeof AppLumiaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mapa': {
      id: '/app/mapa'
      path: '/mapa'
      fullPath: '/app/mapa'
      preLoaderRoute: typeof AppMapaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/ocorrencias': {
      id: '/app/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/app/ocorrencias'
      preLoaderRoute: typeof AppOcorrenciasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/privacidade': {
      id: '/app/privacidade'
      path: '/privacidade'
      fullPath: '/app/privacidade'
      preLoaderRoute: typeof AppPrivacidadeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/registrar': {
      id: '/app/registrar'
      path: '/registrar'
      fullPath: '/app/registrar'
      preLoaderRoute: typeof AppRegistrarRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/institucional/cadastro': {
      id: '/institucional/cadastro'
      path: '/institucional/cadastro'
      fullPath: '/institucional/cadastro'
      preLoaderRoute: typeof InstitucionalCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional/entrar': {
      id: '/institucional/entrar'
      path: '/institucional/entrar'
      fullPath: '/institucional/entrar'
      preLoaderRoute: typeof InstitucionalEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional/esqueci-senha': {
      id: '/institucional/esqueci-senha'
      path: '/institucional/esqueci-senha'
      fullPath: '/institucional/esqueci-senha'
      preLoaderRoute: typeof InstitucionalEsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/': {
      id: '/org/'
      path: '/'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/analises': {
      id: '/org/analises'
      path: '/analises'
      fullPath: '/org/analises'
      preLoaderRoute: typeof OrgAnalisesRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/auditoria': {
      id: '/org/auditoria'
      path: '/auditoria'
      fullPath: '/org/auditoria'
      preLoaderRoute: typeof OrgAuditoriaRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/configuracoes': {
      id: '/org/configuracoes'
      path: '/configuracoes'
      fullPath: '/org/configuracoes'
      preLoaderRoute: typeof OrgConfiguracoesRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/contestacoes': {
      id: '/org/contestacoes'
      path: '/contestacoes'
      fullPath: '/org/contestacoes'
      preLoaderRoute: typeof OrgContestacoesRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/mapa': {
      id: '/org/mapa'
      path: '/mapa'
      fullPath: '/org/mapa'
      preLoaderRoute: typeof OrgMapaRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/notificacoes': {
      id: '/org/notificacoes'
      path: '/notificacoes'
      fullPath: '/org/notificacoes'
      preLoaderRoute: typeof OrgNotificacoesRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/ocorrencias': {
      id: '/org/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/org/ocorrencias'
      preLoaderRoute: typeof OrgOcorrenciasRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/populacao': {
      id: '/org/populacao'
      path: '/populacao'
      fullPath: '/org/populacao'
      preLoaderRoute: typeof OrgPopulacaoRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/previsoes': {
      id: '/org/previsoes'
      path: '/previsoes'
      fullPath: '/org/previsoes'
      preLoaderRoute: typeof OrgPrevisoesRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/relatorios': {
      id: '/org/relatorios'
      path: '/relatorios'
      fullPath: '/org/relatorios'
      preLoaderRoute: typeof OrgRelatoriosRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/auditoria/logs': {
      id: '/org/auditoria/logs'
      path: '/logs'
      fullPath: '/org/auditoria/logs'
      preLoaderRoute: typeof OrgAuditoriaLogsRouteImport
      parentRoute: typeof OrgAuditoriaRoute
    }
    '/org/contestacoes/revisao': {
      id: '/org/contestacoes/revisao'
      path: '/revisao'
      fullPath: '/org/contestacoes/revisao'
      preLoaderRoute: typeof OrgContestacoesRevisaoRouteImport
      parentRoute: typeof OrgContestacoesRoute
    }
    '/org/previsoes/explicacao': {
      id: '/org/previsoes/explicacao'
      path: '/explicacao'
      fullPath: '/org/previsoes/explicacao'
      preLoaderRoute: typeof OrgPrevisoesExplicacaoRouteImport
      parentRoute: typeof OrgPrevisoesRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAlertasRoute: typeof AppAlertasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContestacaoRoute: typeof AppContestacaoRoute
  AppLumiaRoute: typeof AppLumiaRoute
  AppMapaRoute: typeof AppMapaRoute
  AppOcorrenciasRoute: typeof AppOcorrenciasRoute
  AppPrivacidadeRoute: typeof AppPrivacidadeRoute
  AppRegistrarRoute: typeof AppRegistrarRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAlertasRoute: AppAlertasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContestacaoRoute: AppContestacaoRoute,
  AppLumiaRoute: AppLumiaRoute,
  AppMapaRoute: AppMapaRoute,
  AppOcorrenciasRoute: AppOcorrenciasRoute,
  AppPrivacidadeRoute: AppPrivacidadeRoute,
  AppRegistrarRoute: AppRegistrarRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface OrgAuditoriaRouteChildren {
  OrgAuditoriaLogsRoute: typeof OrgAuditoriaLogsRoute
}

const OrgAuditoriaRouteChildren: OrgAuditoriaRouteChildren = {
  OrgAuditoriaLogsRoute: OrgAuditoriaLogsRoute,
}

const OrgAuditoriaRouteWithChildren = OrgAuditoriaRoute._addFileChildren(
  OrgAuditoriaRouteChildren,
)

interface OrgContestacoesRouteChildren {
  OrgContestacoesRevisaoRoute: typeof OrgContestacoesRevisaoRoute
}

const OrgContestacoesRouteChildren: OrgContestacoesRouteChildren = {
  OrgContestacoesRevisaoRoute: OrgContestacoesRevisaoRoute,
}

const OrgContestacoesRouteWithChildren = OrgContestacoesRoute._addFileChildren(
  OrgContestacoesRouteChildren,
)

interface OrgPrevisoesRouteChildren {
  OrgPrevisoesExplicacaoRoute: typeof OrgPrevisoesExplicacaoRoute
}

const OrgPrevisoesRouteChildren: OrgPrevisoesRouteChildren = {
  OrgPrevisoesExplicacaoRoute: OrgPrevisoesExplicacaoRoute,
}

const OrgPrevisoesRouteWithChildren = OrgPrevisoesRoute._addFileChildren(
  OrgPrevisoesRouteChildren,
)

interface OrgRouteRouteChildren {
  OrgAnalisesRoute: typeof OrgAnalisesRoute
  OrgAuditoriaRoute: typeof OrgAuditoriaRouteWithChildren
  OrgConfiguracoesRoute: typeof OrgConfiguracoesRoute
  OrgContestacoesRoute: typeof OrgContestacoesRouteWithChildren
  OrgMapaRoute: typeof OrgMapaRoute
  OrgNotificacoesRoute: typeof OrgNotificacoesRoute
  OrgOcorrenciasRoute: typeof OrgOcorrenciasRoute
  OrgPopulacaoRoute: typeof OrgPopulacaoRoute
  OrgPrevisoesRoute: typeof OrgPrevisoesRouteWithChildren
  OrgRelatoriosRoute: typeof OrgRelatoriosRoute
  OrgIndexRoute: typeof OrgIndexRoute
}

const OrgRouteRouteChildren: OrgRouteRouteChildren = {
  OrgAnalisesRoute: OrgAnalisesRoute,
  OrgAuditoriaRoute: OrgAuditoriaRouteWithChildren,
  OrgConfiguracoesRoute: OrgConfiguracoesRoute,
  OrgContestacoesRoute: OrgContestacoesRouteWithChildren,
  OrgMapaRoute: OrgMapaRoute,
  OrgNotificacoesRoute: OrgNotificacoesRoute,
  OrgOcorrenciasRoute: OrgOcorrenciasRoute,
  OrgPopulacaoRoute: OrgPopulacaoRoute,
  OrgPrevisoesRoute: OrgPrevisoesRouteWithChildren,
  OrgRelatoriosRoute: OrgRelatoriosRoute,
  OrgIndexRoute: OrgIndexRoute,
}

const OrgRouteRouteWithChildren = OrgRouteRoute._addFileChildren(
  OrgRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  OrgRouteRoute: OrgRouteRouteWithChildren,
  AcessoRoute: AcessoRoute,
  CadastroRoute: CadastroRoute,
  EntrarRoute: EntrarRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  OnboardingRoute: OnboardingRoute,
  SairRoute: SairRoute,
  InstitucionalCadastroRoute: InstitucionalCadastroRoute,
  InstitucionalEntrarRoute: InstitucionalEntrarRoute,
  InstitucionalEsqueciSenhaRoute: InstitucionalEsqueciSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
