import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { listRecordsFn, type ManagedRecord, type RecordKind } from "@/lib/records";
import { PageHeader, Panel, StatCard, StatusPill, ConfidenceBar, Disclaimer } from "@/components/sentinela/ui-kit";
import { Button } from "@/components/ui/button";
import { TrendChart } from "@/components/sentinela/charts";

export const Route = createFileRoute("/org/auditoria")({ component: AuditoriaDashboard });
type AuditData = Record<"predictions" | "audits" | "bias_alerts" | "contests" | "mitigations" | "ai_decisions" | "models", ManagedRecord[]>;
const empty: AuditData = { predictions: [], audits: [], bias_alerts: [], contests: [], mitigations: [], ai_decisions: [], models: [] };

function AuditoriaDashboard() {
  const [data, setData] = useState<AuditData>(empty);
  const [loading, setLoading] = useState(true);
  useEffect(() => { const kinds = Object.keys(empty) as Array<keyof AuditData>; void Promise.all(kinds.map((kind) => listRecordsFn({ data: { kind: kind as RecordKind } }))).then((results) => setData(Object.fromEntries(kinds.map((kind, index) => [kind, results[index]])) as AuditData)).finally(() => setLoading(false)); }, []);
  const metrics = useMemo(() => calculate(data), [data]);
  return <div className="space-y-6"><PageHeader title="Central de Auditoria e Transparência" description="Monitore desempenho, equidade, revisões humanas, rastreabilidade e governança da IA." action={<Button asChild variant="secondary"><Link to="/org/auditoria/logs">Consultar trilha de auditoria</Link></Button>} />
    {loading && <Panel><p className="text-sm text-muted-foreground">Calculando indicadores do banco...</p></Panel>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><StatCard label="Modelos monitorados" value={String(data.models.length)} /><StatCard label="Decisões humanas analisadas" value={String(data.ai_decisions.length)} /><StatCard label="Alertas de possível disparidade" value={String(metrics.activeBias)} tone={metrics.activeBias ? "danger" : "success"} /><StatCard label="Auditorias registradas" value={String(data.audits.length)} /><StatCard label="Contestações" value={String(data.contests.length)} tone="warning" /><StatCard label="Correções e mitigações" value={String(data.mitigations.length)} tone="success" /></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Previsões geradas" value={String(data.predictions.length)} /><StatCard label="Previsões revisadas" value={String(metrics.reviewed)} tone="success" /><StatCard label="Não revisadas" value={String(Math.max(0, data.predictions.length - metrics.reviewed))} tone="warning" /><StatCard label="Confiabilidade média" value={`${metrics.averageConfidence}%`} /></div>
    <div className="grid gap-5 xl:grid-cols-3"><Panel title="Status de equidade do sistema" className="xl:col-span-1"><StatusPill tone={metrics.activeBias ? "warning" : "success"}>{metrics.activeBias ? "Necessita investigação" : "Dentro do monitoramento esperado"}</StatusPill><div className="mt-5"><ConfidenceBar value={metrics.equityIndex} label="Índice agregado de monitoramento" /></div><p className="mt-4 text-xs leading-relaxed text-muted-foreground">O índice é um sinal de acompanhamento e não prova discriminação nem determina causalidade.</p><Button asChild size="sm" variant="secondary" className="mt-4"><Link to="/org/equidade">Abrir monitoramento de equidade</Link></Button></Panel><Panel title="Evolução das auditorias" className="xl:col-span-2">{metrics.timeline.some((item) => item.ocorrencias > 0) ? <TrendChart data={metrics.timeline} height={230} /> : <p className="flex h-52 items-center justify-center text-sm text-muted-foreground">A evolução aparecerá após auditorias em diferentes meses.</p>}</Panel></div>
    <Panel title="Monitoramento de possíveis disparidades" subtitle="Métricas agregadas e anonimizadas, utilizadas exclusivamente para auditoria.">{data.bias_alerts.length ? <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="text-muted-foreground"><tr className="border-b border-border"><th className="p-3">Alerta / métrica</th><th className="p-3">Região</th><th className="p-3">Período</th><th className="p-3">Severidade</th><th className="p-3">Status</th></tr></thead><tbody>{data.bias_alerts.map((item) => <tr key={item.id} className="border-b border-border/70"><td className="p-3 font-medium">{item.title}</td><td className="p-3">{item.region}</td><td className="p-3">{item.eventDate}</td><td className="p-3">{item.confidence >= 80 ? "Alta" : item.confidence >= 50 ? "Média" : "Baixa"}</td><td className="p-3"><StatusPill tone={item.status.toLocaleLowerCase().includes("conclu") ? "success" : "warning"}>{item.status}</StatusPill></td></tr>)}</tbody></table></div> : <p className="py-6 text-center text-sm text-muted-foreground">Nenhum alerta de disparidade cadastrado.</p>}</Panel>
    <div className="grid gap-5 xl:grid-cols-2"><Panel title="Última auditoria realizada">{metrics.lastAudit ? <AuditSummary record={metrics.lastAudit} /> : <p className="text-sm text-muted-foreground">Nenhuma auditoria registrada.</p>}</Panel><Panel title="Próxima auditoria"><p className="text-sm font-medium">{metrics.nextAudit}</p><p className="mt-2 text-xs text-muted-foreground">O planejamento deve considerar alertas ativos, alterações do modelo, qualidade dos dados e contestações recebidas.</p><div className="mt-4 flex gap-2"><Button asChild size="sm" variant="secondary"><Link to="/org/governanca-modelos">Ver modelos</Link></Button><Button asChild size="sm" variant="secondary"><Link to="/org/qualidade-dados">Ver qualidade dos dados</Link></Button></div></Panel></div>
    <Panel title="Auditorias e revisões recentes"><div className="space-y-3">{data.audits.slice(0, 6).map((record) => <div key={record.id} className="rounded-lg border border-border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{record.title}</p><p className="mt-1 text-xs text-muted-foreground">{record.eventDate} · {record.eventTime} · {record.source}</p></div><StatusPill tone={record.status.toLocaleLowerCase().includes("conclu") || record.status === "Registrado" ? "success" : "warning"}>{record.status}</StatusPill></div>{record.details && <p className="mt-3 text-sm text-muted-foreground">{record.details}</p>}</div>)}{!data.audits.length && <p className="py-5 text-center text-sm text-muted-foreground">Nenhum registro de auditoria.</p>}</div></Panel>
    <Disclaimer>Indicadores de equidade servem para identificar diferenças que exigem investigação. Características protegidas não devem ser utilizadas para gerar risco individual ou justificar decisões contra pessoas.</Disclaimer>
  </div>;
}

function calculate(data: AuditData) { const reviewed = data.predictions.filter((item) => /revis|conclu|confirm/i.test(item.status)).length; const averageConfidence = data.predictions.length ? Math.round(data.predictions.reduce((sum, item) => sum + item.confidence, 0) / data.predictions.length) : 0; const activeBias = data.bias_alerts.filter((item) => !/conclu|encerr|corrigid/i.test(item.status)).length; const equityIndex = Math.max(0, Math.min(100, 100 - activeBias * 12)); const now = new Date(); const timeline = Array.from({ length: 6 }, (_, index) => { const date = new Date(now.getFullYear(), now.getMonth() - (5 - index), 1); return { mes: date.toLocaleDateString("pt-BR", { month: "short" }), ocorrencias: data.audits.filter((item) => { const event = new Date(`${item.eventDate}T12:00:00`); return event.getMonth() === date.getMonth() && event.getFullYear() === date.getFullYear(); }).length }; }); const sorted = [...data.audits].sort((a, b) => `${b.eventDate}${b.eventTime}`.localeCompare(`${a.eventDate}${a.eventTime}`)); const next = new Date(); next.setDate(next.getDate() + 90); return { reviewed, averageConfidence, activeBias, equityIndex, timeline, lastAudit: sorted[0], nextAudit: next.toLocaleDateString("pt-BR") }; }
function AuditSummary({ record }: { record: ManagedRecord }) { return <dl className="space-y-2 text-sm"><Row label="Auditoria" value={record.title} /><Row label="Responsável / origem" value={record.source} /><Row label="Data" value={record.eventDate} /><Row label="Resultado" value={record.status} />{record.details && <Row label="Detalhes" value={record.details} />}</dl>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 border-b border-border pb-2"><dt className="text-muted-foreground">{label}</dt><dd className="max-w-[65%] text-right">{value}</dd></div>; }
