import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { addRecordFn, listRecordsFn, type ManagedRecord } from "@/lib/records";
import { PageHeader, Panel, StatCard, StatusPill, Disclaimer } from "@/components/sentinela/ui-kit";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";

export const Route = createFileRoute("/org/relatorios")({ component: RelatoriosAuditor });
const reportTypes = ["Relatório de ocorrências", "Relatório de previsões", "Relatório de desempenho da IA", "Relatório de auditoria", "Relatório de contestações", "Relatório de Equidade Algorítmica"] as const;
type ReportType = (typeof reportTypes)[number];
type DataSet = { occurrences: ManagedRecord[]; predictions: ManagedRecord[]; audits: ManagedRecord[]; contests: ManagedRecord[]; bias_alerts: ManagedRecord[]; mitigations: ManagedRecord[]; reports: ManagedRecord[] };
const empty: DataSet = { occurrences: [], predictions: [], audits: [], contests: [], bias_alerts: [], mitigations: [], reports: [] };

function RelatoriosAuditor() {
  const [data, setData] = useState<DataSet>(empty);
  const [type, setType] = useState<ReportType>(reportTypes[0]);
  const [period, setPeriod] = useState("Últimos 30 dias"); const [region, setRegion] = useState("Todas"); const [occurrenceType, setOccurrenceType] = useState("Todos"); const [source, setSource] = useState("Todas"); const [status, setStatus] = useState("Todos");
  const [preview, setPreview] = useState(false); const [message, setMessage] = useState("");
  const load = async () => { const kinds = Object.keys(empty) as Array<keyof DataSet>; const results = await Promise.all(kinds.map((kind) => listRecordsFn({ data: { kind } }))); setData(Object.fromEntries(kinds.map((kind, index) => [kind, results[index]])) as DataSet); };
  useEffect(() => { void load(); }, []);
  const filteredOccurrences = useMemo(() => filterRecords(data.occurrences, period, region, occurrenceType, source, status), [data.occurrences, period, region, occurrenceType, source, status]);
  const content = useMemo(() => buildReport(type, data, filteredOccurrences), [type, data, filteredOccurrences]);
  const generate = async () => { const now = new Date(); await addRecordFn({ data: { kind: "reports", record: { title: type, region, eventDate: now.toISOString().slice(0, 10), eventTime: now.toTimeString().slice(0, 5), source: "Auditoria", status: "Disponível", confidence: content.indicator, details: `Período: ${period}. ${content.summary}` } } }); setMessage("Relatório gerado e registrado no banco."); setPreview(true); await load(); };
  return <div className="space-y-6 print:bg-white print:text-black"><PageHeader title="Relatórios do Auditor" description="Gere, visualize e exporte relatórios de ocorrências, previsões, auditoria, contestações e equidade algorítmica." />
    <Panel title="Configurar relatório"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><SelectField label="Tipo de relatório" value={type} options={[...reportTypes]} onChange={(value) => setType(value as ReportType)} /><SelectField label="Período" value={period} options={["Últimos 7 dias", "Últimos 30 dias", "3 meses", "12 meses"]} onChange={setPeriod} /><SelectField label="Região" value={region} options={["Todas", ...unique(data.occurrences.map((item) => item.region))]} onChange={setRegion} /><SelectField label="Tipo de ocorrência" value={occurrenceType} options={["Todos", ...unique(data.occurrences.map((item) => item.title))]} onChange={setOccurrenceType} /><SelectField label="Origem" value={source} options={["Todas", ...unique(data.occurrences.map((item) => item.source))]} onChange={setSource} /><SelectField label="Status" value={status} options={["Todos", ...unique(data.occurrences.map((item) => item.status))]} onChange={setStatus} /></div><div className="mt-5 flex flex-wrap gap-3"><Button onClick={generate}>Gerar relatório</Button><Button variant="secondary" onClick={() => setPreview(true)}>Visualizar</Button><Button variant="secondary" onClick={() => exportData(type, content.rows)}>Exportar dados</Button><Button variant="secondary" onClick={() => { setPreview(true); window.setTimeout(() => window.print(), 100); }}>Exportar PDF</Button></div>{message && <p className="mt-3 text-sm text-success">{message}</p>}</Panel>
    {preview && <section id="audit-report" className="space-y-5"><Panel title={type} subtitle={`Período: ${period} · Região: ${region}`} action={<StatusPill tone="success">Gerado com dados do banco</StatusPill>}><p className="text-sm leading-relaxed text-muted-foreground">{content.summary}</p></Panel><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Registros analisados" value={String(content.total)} /><StatCard label={content.indicatorLabel} value={`${content.indicator}%`} /><StatCard label="Contestações" value={String(data.contests.length)} tone="warning" /><StatCard label="Correções realizadas" value={String(data.mitigations.length)} tone="success" /></div>
      {type === "Relatório de Equidade Algorítmica" && <Panel title="Seções do Relatório de Equidade"><ol className="grid gap-3 text-sm sm:grid-cols-2 xl:grid-cols-3">{["1. Modelo analisado", "2. Período", "3. Dados utilizados", "4. Métricas de desempenho", "5. Métricas de equidade", "6. Disparidades encontradas", "7. Possíveis causas investigadas", "8. Contestações recebidas", "9. Revisões humanas", "10. Correções realizadas", "11. Limitações", "12. Recomendações"].map((item) => <li key={item} className="rounded-lg border border-border p-3">{item}</li>)}</ol></Panel>}
      <Panel title="Dados consolidados">{content.rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead><tr className="border-b border-border text-muted-foreground"><th className="p-3">Título</th><th className="p-3">Região</th><th className="p-3">Data</th><th className="p-3">Origem</th><th className="p-3">Status</th><th className="p-3">Confiabilidade</th></tr></thead><tbody>{content.rows.slice(0, 100).map((item) => <tr key={item.id} className="border-b border-border/70"><td className="p-3 font-medium">{item.title}</td><td className="p-3">{item.region}</td><td className="p-3">{item.eventDate}</td><td className="p-3">{item.source}</td><td className="p-3">{item.status}</td><td className="p-3">{item.confidence}%</td></tr>)}</tbody></table></div> : <p className="py-6 text-center text-sm text-muted-foreground">Nenhum dado encontrado com estes filtros.</p>}</Panel>
      <Disclaimer>Este relatório apresenta dados agregados. Diferenças observadas exigem investigação contextual e não devem ser usadas para classificar indivíduos ou determinar causalidade automaticamente.</Disclaimer></section>}
    <Panel title="Histórico de relatórios gerados"><div className="space-y-3">{data.reports.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border p-4"><div><p className="font-semibold">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.eventDate} · {item.eventTime} · {item.details}</p></div><StatusPill tone="success">{item.status}</StatusPill></div>)}{!data.reports.length && <p className="text-sm text-muted-foreground">Nenhum relatório gerado.</p>}</div></Panel>
  </div>;
}

function filterRecords(rows: ManagedRecord[], period: string, region: string, type: string, source: string, status: string) { const days = period === "Últimos 7 dias" ? 7 : period === "3 meses" ? 90 : period === "12 meses" ? 365 : 30; const cutoff = new Date(); cutoff.setDate(cutoff.getDate() - days); return rows.filter((item) => (!item.eventDate || new Date(`${item.eventDate}T12:00:00`) >= cutoff) && (region === "Todas" || item.region === region) && (type === "Todos" || item.title === type) && (source === "Todas" || item.source === source) && (status === "Todos" || item.status === status)); }
function buildReport(type: ReportType, data: DataSet, occurrences: ManagedRecord[]) { let rows = occurrences; if (type === "Relatório de previsões" || type === "Relatório de desempenho da IA") rows = data.predictions; if (type === "Relatório de auditoria") rows = data.audits; if (type === "Relatório de contestações") rows = data.contests; if (type === "Relatório de Equidade Algorítmica") rows = [...data.bias_alerts, ...data.audits, ...data.mitigations]; const indicator = rows.length ? Math.round(rows.reduce((sum, item) => sum + item.confidence, 0) / rows.length) : 0; return { rows, total: rows.length, indicator, indicatorLabel: type.includes("Equidade") ? "Índice monitorado" : "Confiabilidade média", summary: `${rows.length} registros foram consolidados. A média do indicador disponível é ${indicator}%. Os resultados devem ser interpretados em conjunto com limitações, origem e qualidade dos dados.` }; }
function unique(values: string[]) { return [...new Set(values.filter(Boolean))].sort((a, b) => a.localeCompare(b, "pt-BR")); }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <div className="space-y-2"><Label>{label}</Label><select value={value} onChange={(event) => onChange(event.target.value)} className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{options.map((option) => <option key={option}>{option}</option>)}</select></div>; }
function exportData(type: string, rows: ManagedRecord[]) { const header = ["Título", "Região", "Data", "Horário", "Origem", "Status", "Confiabilidade", "Detalhes"]; const escape = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`; const csv = [header, ...rows.map((item) => [item.title, item.region, item.eventDate, item.eventTime, item.source, item.status, item.confidence, item.details])].map((row) => row.map(escape).join(";")).join("\n"); const blob = new Blob(["\uFEFF", csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${type.toLocaleLowerCase("pt-BR").replace(/[^a-z0-9]+/gi, "-")}.csv`; anchor.click(); URL.revokeObjectURL(url); }
